# Generated by Django 2.2.6 on 2019-12-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'مشاور', 'verbose_name_plural': 'مشاور'},
        ),
        migrations.AlterModelOptions(
            name='consultanteducation',
            options={'verbose_name': 'تحصیلات مشاور', 'verbose_name_plural': 'تحصیلات های مشاور'},
        ),
        migrations.AlterModelOptions(
            name='consultantexperience',
            options={'verbose_name': 'تجربه کاری مشاور', 'verbose_name_plural': 'تجربیات کاری مشاور'},
        ),
        migrations.AlterModelOptions(
            name='consultantskill',
            options={'verbose_name': 'مهارت مشاور', 'verbose_name_plural': 'مهارت های مشاور'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات ها'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'تجربه کاری', 'verbose_name_plural': 'تجربیات کاری'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'امتیاز', 'verbose_name_plural': 'امتیاز ها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AlterField(
            model_name='consultant',
            name='activity',
            field=models.CharField(max_length=255, null=True, verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='address',
            field=models.TextField(max_length=512, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='consultant_cv', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='educations',
            field=models.ManyToManyField(blank=True, through='consultant.ConsultantEducation', to='consultant.Education', verbose_name='تحصیلات ها'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='experiences',
            field=models.ManyToManyField(blank=True, through='consultant.ConsultantExperience', to='consultant.Experience', verbose_name='تجربیات کاری'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='father_name',
            field=models.CharField(max_length=255, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='mobile_number',
            field=models.CharField(max_length=13, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='rate_average', to='consultant.Rate', verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='skills',
            field=models.ManyToManyField(blank=True, through='consultant.ConsultantSkill', to='consultant.Skill', verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='آدرس تلگرام'),
        ),
        migrations.AlterField(
            model_name='consultanteducation',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_attributes', to='consultant.Consultant', verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='consultanteducation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='consultanteducation',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Education', verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='consultantexperience',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_attributes', to='consultant.Consultant', verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='consultantexperience',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Experience', verbose_name='تجربه کاری'),
        ),
        migrations.AlterField(
            model_name='consultantskill',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_attributes', to='consultant.Consultant', verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='consultantskill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='consultantskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Skill', verbose_name='مهارت'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=255, verbose_name='دانشگاه'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultant.Consultant', verbose_name='مشاور'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.SmallIntegerField(default=5, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='عنوان'),
        ),
    ]
