# Generated by Django 2.2.6 on 2020-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_auto_20191231_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='is_enabled'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='rate_average', to='consultant.Rate', verbose_name='rating'),
        ),
    ]
