version: '3'

services:
  backend:
    build: .
    container_name: mehrgan-backend
    restart: always
    ports:
      - '8006:8001'
    command: bash -c "export environment=docker.env && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
