# Generated by Django 2.2.6 on 2019-12-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizeditems',
            options={'verbose_name': 'دسته بندی شده ها', 'verbose_name_plural': 'دسته بندی شده ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='commenteditems',
            options={'verbose_name': 'نظر دهی شده ها', 'verbose_name_plural': 'نظر دهی شده ها'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوالات متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=989123456789, max_length=13, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorizeditems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='categorizeditems',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='categorizeditems',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='شماره شی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Category', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='category_thumbnail', verbose_name='عکس برگزیده'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Comment', verbose_name='پدر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='commenteditems',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment', verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='commenteditems',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='نوع محتوا'),
        ),
        migrations.AlterField(
            model_name='commenteditems',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='شماره شی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=500, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('read', 'خوانده شده'), ('unread', 'خوانده نشده')], default='unread', max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
