# Generated by Django 2.2.6 on 2019-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191231_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEditForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=255, verbose_name='company_type')),
                ('company_type_change', models.CharField(max_length=255, verbose_name='company_type_change')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('region', models.CharField(max_length=255, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'company_edit_form',
                'verbose_name_plural': 'company_edit_forms',
                'db_table': 'company_edit_forms',
            },
        ),
        migrations.CreateModel(
            name='CompanyRegisterForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=255, verbose_name='company_type')),
                ('activity', models.CharField(max_length=255, verbose_name='فعالیت')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('region', models.CharField(max_length=255, verbose_name='region')),
                ('fund', models.CharField(max_length=255, verbose_name='fund')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'company_register_form',
                'verbose_name_plural': 'company_register_forms',
                'db_table': 'company_register_forms',
            },
        ),
        migrations.CreateModel(
            name='CompanyRegisterTrademarksForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_type', models.CharField(max_length=255, verbose_name='trademark_type')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('is_extended', models.BooleanField(default=True, verbose_name='is_extended')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'company_register_trademarks_form',
                'verbose_name_plural': 'company_register_trademarks_forms',
                'db_table': 'company_register_trademarks_forms',
            },
        ),
        migrations.CreateModel(
            name='LegalAdviceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(max_length=255, verbose_name='advice_type')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'legal_advice_form',
                'verbose_name_plural': 'legal_advice_forms',
                'db_table': 'legal_advice_forms',
            },
        ),
        migrations.CreateModel(
            name='OfficialServicesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=255, verbose_name='service_type')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'official_services_form',
                'verbose_name_plural': 'official_services_forms',
                'db_table': 'official_services_forms',
            },
        ),
        migrations.CreateModel(
            name='RequestLawyerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=255, verbose_name='request_type')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_tracked', models.BooleanField(default=False, verbose_name='is_tracked')),
            ],
            options={
                'verbose_name': 'request_lawyer_form',
                'verbose_name_plural': 'request_lawyer_forms',
                'db_table': 'request_lawyer_forms',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
    ]
