# Generated by Django 2.2.6 on 2019-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191231_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyeditform',
            options={'verbose_name': 'فرم تغییر شرکت', 'verbose_name_plural': 'فرم های تغییر شرکت'},
        ),
        migrations.AlterModelOptions(
            name='companyregisterform',
            options={'verbose_name': 'فرم ثبت شرکت', 'verbose_name_plural': 'فرم های ثبت شرکت'},
        ),
        migrations.AlterModelOptions(
            name='companyregistertrademarksform',
            options={'verbose_name': 'فرم ثبت علایم تجاری', 'verbose_name_plural': 'فرم های ثبت علایم تجاری'},
        ),
        migrations.AlterModelOptions(
            name='legaladviceform',
            options={'verbose_name': 'فرم مشاوره حقوقی', 'verbose_name_plural': 'فرم های مشاوره حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='officialservicesform',
            options={'verbose_name': 'فرم خدمات اداری', 'verbose_name_plural': 'فرم های خدمات اداری'},
        ),
        migrations.AlterModelOptions(
            name='requestlawyerform',
            options={'verbose_name': 'فرم درخواست وکیل', 'verbose_name_plural': 'فرم های درخواست وکیل'},
        ),
        migrations.AlterField(
            model_name='companyeditform',
            name='company_type',
            field=models.CharField(max_length=255, verbose_name='نوع شرکت'),
        ),
        migrations.AlterField(
            model_name='companyeditform',
            name='company_type_change',
            field=models.CharField(max_length=255, verbose_name='تغییر نوع شرکت به'),
        ),
        migrations.AlterField(
            model_name='companyeditform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='companyeditform',
            name='region',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='company_type',
            field=models.CharField(max_length=255, verbose_name='نوع شرکت'),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='fund',
            field=models.CharField(max_length=255, verbose_name='سرمایه'),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='companyregisterform',
            name='region',
            field=models.CharField(max_length=255, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='companyregistertrademarksform',
            name='is_extended',
            field=models.BooleanField(default=True, verbose_name='آیا تمدید می خواهد؟'),
        ),
        migrations.AlterField(
            model_name='companyregistertrademarksform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='companyregistertrademarksform',
            name='trademark_type',
            field=models.CharField(max_length=255, verbose_name='نوع علامت تجاری'),
        ),
        migrations.AlterField(
            model_name='legaladviceform',
            name='advice_type',
            field=models.CharField(max_length=255, verbose_name='نوع مشاوره'),
        ),
        migrations.AlterField(
            model_name='legaladviceform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='officialservicesform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='officialservicesform',
            name='service_type',
            field=models.CharField(max_length=255, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='requestlawyerform',
            name='is_tracked',
            field=models.BooleanField(default=False, verbose_name='آیا پیگیری شده است؟'),
        ),
        migrations.AlterField(
            model_name='requestlawyerform',
            name='request_type',
            field=models.CharField(max_length=255, verbose_name='نوع درخواست'),
        ),
    ]
