# Generated by Django 2.2.6 on 2019-12-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191231_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.IntegerField(verbose_name='زمان'),
        ),
    ]
